### PR TITLE
Removed warns length parameter and renamed warnsexpiriation 

### PR DESCRIPTION
**Pull request by potatomantiger**

### CODE REVIEW

**Review by UserR00T — COMMENTED** [review]
Could you please elaborate what you changed within these files? I do not seem to understand exactly what `length` was supposed to do and why it is replaced now.

**Review by PLASMAchicken — APPROVED** [review]

**Comment by PLASMAchicken** [comment]
length was added by G's Code, as mine was based on it was left in, but it just adds useless overhead to the warn command ( now needing to use "reason with spaces" ) 

Length was added to make a warn expire in eg. 15 days instead of the full 30 (default), but we have come the the conclusion that its utterly useless and only makes everything more complex.

**Comment by potatomantiger** [comment]
> Could you please elaborate what you changed within these files? I do not seem to understand exactly what `length` was supposed to do and why it is replaced now.

basically the g made a thing that lets you set a certain time for warns to expire and also made the warn command have to be used like this /warn name "reason with spaces" and we saw that that was just useless and made it more complex so i removed it

**Review by UserR00T — APPROVED** [review]
Alright, thank you both for explaining and thank you potato for your contribution.

**Pull request merged**
